### ISSUE TITLE
Fails to start on DLL loading error.

### ISSUE THREAD

**Issue by revident** [modzero/fix-windows-privacy#2]
Installed MSI package from today, and the applications fails to load.

* Launching as a user or administrator makes no different.
* running fix-privacy-gui.exe produces no errors and never creates a window.
* running fix-privacy-con.ext produces the error listed below. 
  * the dll is clearly in the same directory which would be part of the standard search path, suggesting the 'file not found' result is misleading. Possible missing dependencies?

Systems is stock install.
Edition: Windows 10 Pro
Version: 1607
14393.447

Please advise on what information I can gather to help further troubleshoot my case.
```
 Directory of C:\Program Files\modzero\fix-windows-privacy

11/15/2016  11:33 AM    <DIR>          .
11/15/2016  11:33 AM    <DIR>          ..
10/31/2016  11:52 AM           105,056 eye_mod0_banner.bmp
10/31/2016  11:52 AM           455,432 eye_mod0_splash.bmp
11/13/2016  08:38 PM           102,448 fix-privacy-cons.exe
11/13/2016  08:38 PM            13,872 fix-privacy-db.DLL
11/13/2016  08:38 PM            47,664 fix-privacy-dll.dll
11/13/2016  08:37 PM           157,360 fix-privacy-gui.exe
11/12/2016  02:44 PM           127,561 FixprivPolicyRules.xml
11/12/2016  01:48 PM             4,839 FixprivServiceRules.xml
11/08/2016  01:07 AM             2,211 LICENSE.txt
10/31/2016  11:52 AM            62,455 mod0-fwp.ico
11/05/2016  01:11 PM                 0 README.md
11/12/2016  01:37 PM             3,684 TODO.md
              12 File(s)      1,082,582 bytes
               2 Dir(s)  34,838,433,792 bytes free

C:\Program Files\modzero\fix-windows-privacy>fix-privacy-cons.exe

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'fix-privacy-dll.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at fix_privacy.Program.fixpriv_elevate_withargs(StringBuilder av)
   at fix_privacy.Program.Main(String[] args)

C:\Program Files\modzero\fix-windows-privacy>
```

**Comment by blueringio** [comment]
Identified this same issue but on only 1 of 4 systems. Will investigate further.

**Comment by devio** [comment]
Thanks for the detailed description, I'm trying to reproduce the issue and will get back to you as soon as I have an idea.

**Comment by devio** [comment]
Are you running a 32 or 64 bit version of Windows 10?

**Comment by fBdoFM** [comment]
Had the same issue. Installed Visual C++ Redistributable for Visual Studio 2015 x64 and it's runnig now. https://www.microsoft.com/en-us/download/details.aspx?id=48145  You should bundle it in your installer. Great job btw :)

**Comment by revident** [comment]
> Are you running a 32 or 64 bit version of Windows 10?

My case is a 64bit installation.

**Comment by revident** [comment]
@devio I've installed the Visual C++ Redistributable for Visual Studio 2015 x64 as recommended by @fBdoFM 
* Command line utility prompts for Administrator (while as a regular user), and starts a new terminal window.
* GUI prompts for Administrator (while as a regular user), and starts a new window.

This looks like expected behavior, and I'm not seeing any new messages in the command line.

As this software was publicized via hackernews, initial users are likely to be developers or power users with a lot of applications installed, making these C++ run times more likely to be installed. I'm mainly a Linux admin and desktop user, as such I've so far kept my windows install lean.

**Comment by devio** [comment]
Fixed by adding Microsoft_VC140_CRT_x64.msm to installer. Thanks for your help!
