### ISSUE TITLE
SHA1 hash does not match current download

### ISSUE THREAD

**Issue by blueringio** [modzero/fix-windows-privacy#4]
Page here - https://modzero.github.io/fix-windows-privacy7 says "SHA1 hash: 9CA607786293B016FC148FC0F09C23CD89BEB2BD"

Hash for file I downloaded today is SHA1 7543EE6819C0E0F6471BFBA046D6730A2DC3AC0F

Please confirm/update. Thanks

**Comment by devio** [comment]
9CA607786293B016FC148FC0F09C23CD89BEB2BD is the hash of the code signing certificate, not the executable/installer. If the code signature is intact and the key matches the hash above, everything is fine.
