### ISSUE TITLE
No support for 32 bit

### ISSUE THREAD

**Issue by fedelebrero** [modzero/fix-windows-privacy#8]
When I try to launch the msi package I obtain an error about This package is not compatible with this processor, while using Win10/x86.

With Win10/x64 runs fine.

Any plans to support 32bit systems?

**Comment by devio** [comment]
I'm sorry, i don't have plans to support 32bit at the moment - however, after fixing the most important issues, i'll think about it again. Maybe it's not an issue at all, to prepare a 32bit version, but i don't believe in the future of 32bit machines ;)
