### ISSUE TITLE
How do you know these registry keys are not normal

### ISSUE THREAD

**Issue by mrbaowei** [modzero/fix-windows-privacy#9]
Please tell me as soon as possible,thanks~

**Comment by devio** [comment]
Well, these settings and policies are "normal" (which is quite relative); it just depends on your point of view. there are several sources on the Internet (see https://modzero.github.io/fix-windows-privacy/) that i included in my decisions, and i also read through the windows registry and Microsoft's documentation to decide if a setting/policy is bad for your privacy. However, i understand that e.g. OneDrive might be an important feature for many people - thus i will add the possibility to exclude certain rules in the future.

**Comment by mrbaowei** [comment]
thanks ,I just want to know more about windows regedit.
